### ISSUE TITLE
the number of beds are not modified in the UI

### ISSUE THREAD

**Issue by SergeStinckwich** [tomooda/IDAIR#6]
When you change the number of regular beds or ICU beds this is not reflected in the interface.

If I change the beds to 5

<img width="529" alt="Screenshot 2023-10-04 at 14 06 04" src="https://github.com/tomooda/IDAIR/assets/327334/c88f41b4-29c3-4ae5-9b44-875a487ece85">

nothing happens in the UI

<img width="282" alt="Screenshot 2023-10-04 at 14 05 25" src="https://github.com/tomooda/IDAIR/assets/327334/2c1f5a1b-0c4a-42ee-8bb9-255b72dc2593">

**Comment by tomooda** [comment]
It's on purpose because the phrase "Occupy 1 ICU bed" is printed on the action cards.

**Comment by tanyiroe** [comment]
Maybe to make it less confusing, we can put 'Occupy ICU bed' and 'Occupy regular bed' in the ABM

**Comment by tomooda** [comment]
This issue must be discussed with the card design on RPG side first.

**Comment by tanyiroe** [comment]
I discussed with Manh, and we modified the card design so that the ABM and RPG can sync better. The new design is as attached. So, can we modify the ABM wording to 'occupy ICU bed', then the pop up says 'Number of patients newly allocated to ICU beds'? Likewise for regular beds.
![image](https://github.com/tomooda/IDAIR/assets/146925601/4b345419-51e5-42c8-b419-fe6ec7479046)

**Comment by tomooda** [comment]
Great! Yes, I'll change the name of the action card.

**Comment by tomooda** [comment]
solved by https://github.com/tomooda/IDAIR/commit/d69c11be358de91dc57ab3829074683a828d1764
